version: '3.4'

services:
  catalog:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: src/Services/MicroserviceCommunication.Catalog/Dockerfile
    depends_on:
      - catalogData

  catalogData:
    image: postgres

  adminer:
    image: adminer