version: '3.4'

services:

  catalogData:
    container_name: catalogData
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - catalogData:/data/postgres

  adminer:
    restart: always
    ports:
      - 8080:8080

  catalog:
    container_name: catalog
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Default=Server=catalogData;Database=catalogData;Port=5432;User Id=usr;Password=password;
    ports:
      - "5001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  basket:
    container_name: basket
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"

volumes:
  catalogData:
