version: '3.4'

services:
  catalogData:
    image: postgres

  adminer:
    image: adminer

  catalog:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: src/Services/MicroserviceCommunication.Catalog/Dockerfile
    depends_on:
      - catalogData

  basket:
    image: ${DOCKER_REGISTRY-}basket
    build:
      context: .
      dockerfile: src/Services/MicroserviceCommunication.Basket/Dockerfile